name: bgcz
on: 
  push:
    branches:
     - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@master
      
    - name: test
      uses: ./actions/node8
      
    - name: createIssueByLables
      uses: ZjBlog/create-issue-by-lables@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
        filepath: issues.json
    
    - name: deplay
      uses: ./actions/deploy
      env:
        REPO:  "bgcz/bgcz.github.io"
        TOKENACTION:  ${{ secrets.TOKENACTION }}
     
    - name: send-message
      uses: ZjBlog/message@v1.5
      with:
        URL:  ${{ secrets.URL}}
      env: 
        MESSAGE: "bgcz.github.io部署成功"
      
