name: bgcz
on: 
  push:
    branches:
     - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - uses: ./actions/node8
    - name: send-message
      uses: ZjBlog/message@v1.0
      with:
        URL:  ${{ secrets.URL}}
      env: 
        MESSAGE: "bgcz.github.io部署成功"
      
